### ISSUE TITLE
baseURL doesn't place in server side

### ISSUE THREAD

**Issue by ErriourMe** [nuxt-alt/http#1]
I am using a config and connect it to `nuxt.config`:
```
import { ModuleOptions } from '@nuxt-alt/http/dist/types'

export const httpConfig: ModuleOptions = {
  baseURL: 'http://localhost:3333',
  browserBaseURL: 'http://localhost:3333',
  debug: false,
  retry: 0,
}
```

Previously, in @nuxtjs-alt/http 1.5.3 all works fine. But now (@nuxt-alt/http 1.5.5) I can't get baseURL in server side, so all requests goes to the client address (in 404), and client side still gets baseURL and works.

I can handle it in interceptor before request
```
$http.interceptors.request.use((httpConfig) => {
    httpConfig.baseURL = 'http://localhost:3333'
    ...
})
```
but it's a little bit crutch.
Can you fix it?

**Comment by Teranode** [comment]
are you using windows?

**Comment by ErriourMe** [comment]
> are you using windows?

Yes, in dev

**Comment by Teranode** [comment]
ah, update to 1.5.6

**Comment by ErriourMe** [comment]
Works fine now, thanks!
