### ISSUE TITLE
baseURL setting doesn't seem to work

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt-alt/http#2]
Just switched from `nuxtjs-alt/auth` and `nuxtjs-alt/http` and it seems like

```ts
http: {
  baseURL: ...
}
```

is not respected.

Neither for requests like `$http.$get(...)`, nor in `nuxt-alt/auth` functions.

I saw there was a related issue with SSR, but my app is running with `ssr: false`.

**Comment by toniengelhardt** [comment]
Setting `browserBaseURL` seems to work.

**Comment by Teranode** [comment]
browserbaseURL is for client side
baseURL is for server side

**Comment by toniengelhardt** [comment]
Works! Thanks a lot for clarifying.
