### ISSUE TITLE
Can't fully use this module and $fetch at the same time

### ISSUE THREAD

**Issue by ttonyh** [nuxt-alt/http#4]
It seems like this module overrides $http (nuxt/http) so trying to do this for example (below) applies to this module and not nuxt/http, affecting the use of $fetch.

```
$http.setHeader('my-header', value);
```

When the above is called, the header is globally set for this module, but not for $fetch.

Is there a workaround or is there a way to gain access to the original $http (nuxt/http) object?

**Comment by Teranode** [comment]
it is an alternative version for nuxt/http. This module and nuxt/http should not be used together
