### ISSUE TITLE
Remove @nuxt/schema overrides

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt-alt/http#9]
The module exports `@nuxt/schema` overrides:

https://github.com/nuxt-alt/http/blob/7162d2c70fb319d4a6414c3296cb3a512460b6f7/src/types.ts#L56-L58

This is however not needed in (modern) Nuxt as it generates `.nuxt/types/schema.d.ts` automatically for all enabled modules and the provided config data:

```ts
import { NuxtModule, RuntimeConfig } from 'nuxt/schema'
declare module 'nuxt/schema' {
   // ...
   interface PublicRuntimeConfig {
   // ...
   http: {
      browserBaseURL: string,
   },
```

The types exported by the module shadow the generated types, and make `http` optional even when it's explicitly provided by user. As the result, user has to use non-null assertions `this.$config.public.http!.browserBaseURL!` every time they want to access module config.

Simply removing built-in `@nuxt/schema` overrides will make simpler code and better DX.

**Comment by Denoder** [comment]
i've removed the typings in the latest version
